"""create_assessments_table

Revision ID: 0f70ef3568cf
Revises: b14a26ab944c
Create Date: 2026-09-03 02:46:51.462266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f70ef3568cf'
down_revision: Union[str, Sequence[str], None] = 'b14a26ab944c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interaction_id', sa.Uuid(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('emotion_label', sa.String(length=50), nullable=True),
    sa.Column('voice_stress_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_interaction_id'), ['interaction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_interaction_id'))

    op.drop_table('assessments')
    # ### end Alembic commands ###
