"""create_distress_scores_table

Revision ID: 97a56dc4ac20
Revises: 0f70ef3568cf
Create Date: 2026-09-03 03:08:39.204935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a56dc4ac20'
down_revision: Union[str, Sequence[str], None] = '0f70ef3568cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distress_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('baseline_score', sa.Float(), nullable=False),
    sa.Column('trend_slope', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    with op.batch_alter_table('distress_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distress_scores_case_id'), ['case_id'], unique=False)
        batch_op.create_index('ix_distress_scores_case_id_computed_at', ['case_id', 'computed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distress_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_distress_scores_case_id_computed_at')
        batch_op.drop_index(batch_op.f('ix_distress_scores_case_id'))

    op.drop_table('distress_scores')
    # ### end Alembic commands ###
