"""create_interactions_table

Revision ID: b14a26ab944c
Revises: 12f7ca8cb60c
Create Date: 2026-09-03 02:27:16.530102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14a26ab944c'
down_revision: Union[str, Sequence[str], None] = '12f7ca8cb60c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('raw_ref_pointer', sa.String(length=255), nullable=True),
    sa.Column('response_latency_sec', sa.Integer(), nullable=True),
    sa.Column('was_skipped', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_case_id'), ['case_id'], unique=False)
        batch_op.create_index('ix_interactions_case_id_occurred_at', ['case_id', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index('ix_interactions_case_id_occurred_at')
        batch_op.drop_index(batch_op.f('ix_interactions_case_id'))

    op.drop_table('interactions')
    # ### end Alembic commands ###
